version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: kingdom_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kingdom_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  api:
    build: ./server
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://kingdom_user:password@db:5432/kingdom_db
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000

# Servicio de Prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api
      - db

# Servicio de Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus


volumes:
  db_data:
